// <auto-generated />
namespace SriLankanLifeVS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedatetimeobjecttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatetimeobjecttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201602020600128_change-datetime-object-to-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
