// <auto-generated />
namespace SriLankanLifeVS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changesliderimagedatamodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesliderimagedatamodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201602020520125_change-slider-image-data-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
